apiVersion: v1
kind: Service
metadata:
    name: feedstarter-service
spec:
  ports:
    - name: silo-port
      port: 11111
      targetPort: 11111
#      nodePort: 11111
    - name: gateway-port
      port: 30000
      targetPort: 30000
#      nodePort: 30000
    - name: silo-silo-port
      port: 40000
      targetPort: 40000
#      nodePort: 40000
    - name: silo-client-port
      port: 50000
      targetPort: 50000
#      nodePort: 50000
    - name: https
      port: 5001
      targetPort: 5001
    - name: httpa
      port: 5002
      targetPort: 5002     
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: feedstarter
  type: LoadBalancer




# ---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: minimal-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /dashboard
#         pathType: Prefix
#         backend:
#           service:
#             name: silo
#             port:
#               number: 80